# Fraud Detection System Configuration

# Data Configuration
data:
  raw_data_path: "data/raw/Fraud.csv"
  processed_data_path: "data/processed/"
  test_size: 0.2
  validation_size: 0.2
  random_state: 42

# Model Configuration
models:
  logistic_regression:
    max_iter: 1000
    class_weight: "balanced"
    random_state: 42
    solver: "liblinear"
  
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    class_weight: "balanced"
    random_state: 42
    n_jobs: -1
  
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    eval_metric: "logloss"
    use_label_encoder: false

# Feature Engineering Configuration
feature_engineering:
  large_transfer_threshold: 200000
  balance_ratio_threshold: 0.1
  merchant_prefix: "M"

# Model Evaluation Configuration
evaluation:
  cv_folds: 5
  scoring_metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
    - "roc_auc"
  threshold: 0.5

# Fraud Detection Service Configuration
fraud_detection:
  alert_threshold: 0.8
  batch_size: 1000
  max_concurrent_requests: 10

# Visualization Configuration
visualization:
  figure_size: [12, 8]
  color_palette: "viridis"
  save_plots: true
  plot_format: "png"
  dpi: 300

# Model Storage Configuration
model_storage:
  model_dir: "models/"
  model_format: "joblib"
  versioning: true
  
# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  
# Dashboard Configuration
dashboard:
  title: "Fraud Detection System"
  port: 8501
  theme: "light"